#!/bin/bash

 
REF_ARRAY=($(ls -1 *rep.fa))

for CURRENTREF in "${REF_ARRAY[@]}"
do
echo "Currentref" $CURRENTREF
CURRENTFASTA=$(echo $CURRENTREF | sed 's/_rep//')
echo "Currentfasta" $CURRENTFASTA
OUTPREFIX=$(echo $CURRENTFASTA | rev | cut -c4- | rev)
echo "out p[refix" $OUTPREFIX
minimap2 --secondary=no -ax asm5 -o $OUTPREFIX.sam $CURRENTREF $CURRENTFASTA  &> $OUTPREFIX.samlog
minimap2 --secondary=no -x asm5 -o $OUTPREFIX.paf $CURRENTREF $CURRENTFASTA  &> $OUTPREFIX.paflog
#minimap2 --help
#minimap2 --secondary=no -x asm5 SHV_12.1_rep.fa SHV_12.1.fa > SHV_12.1_minimap.paf
done
