---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# blantyreESBL

<!-- badges: start -->
<!-- badges: end -->

The blantyreESBL R package is a repository for data generated as part of a study into carriage of resistant bacteria in Blantyre, Malawi. It also includes reproducible analysis script for three manuscripts arising from the study:
  
**Dynamics of gut mucosal colonisation with extended spectrum beta-lactamase producing Enterobacterales in Malawi**

Joseph M Lewis^1,2,3,4^, , Madalitso Mphasa^1^, Rachel Banda^1^,  Matthew Beale^4^, Eva Heinz^2^, Jane Mallewa^5^, Christopher Jewell^6^, Nicholas R Thomson^4,7^, Nicholas A Feasey^1,2^

**Genomic analysis of extended-spectrum beta-lactamase (ESBL) producing Escherichia coli colonising adults in Blantyre, Malawi reveals previously undescribed diversity**

Joseph M Lewis^1,2,3,4^, , Madalitso Mphasa^1^, Rachel Banda^1^,  Matthew Beale^4^, Jane Mallewa^5^, Adam P Roberts^2^, Eva Heinz^2^, Nicholas Thomson^4,7^, Nicholas A Feasey^1,2^

**Genomic and antigenic diversity of carried _Klebsiella pneumoniae_ isolates mirrors that of invasive isolates in Blantyre, Malawi**

Joseph M Lewis^1,2,3,4^, , Madalitso Mphasa^1^, Rachel Banda^1^,  Matthew Beale^4^, Jane Mallewa^5^, Eva Heinz^2^, Nicholas Thomson^4,7^, Nicholas A Feasey^1,2^

### Installing and accessing data

If you just want the data, then all the data to replicate the analysis are bundled with the package. To install the package from GitHub:

``` r
install.packages("devtools")
devtools::install_github("https://github.com/joelewis101/blantyreESBL)
```

The various data objects are described in the [pkgdown](https://joelewis101.github.io/blantyreESBL/) site for this package, and available via R in the usual way (i.e. `?btESBL_participants` brings up the definitions for the `btESBL_participants` data. They are all lazy loaded so will be available for use immediately; they all start with `btESBL_` to make it easy to choose the one you want using autocomplete.

### Analysis scripts

The analysis script to reproduce tables and figures for each manuscript is available as package vignettes; these can be built when downloading the package by running:

``` r
devtools::install_github(
  "https://github.com/joelewis101/blantyreESBL", 
  build_vignettes = TRUE, 
  dependencies = TRUE )
```

The `dependencies = TRUE` option will install all the packages necessary to run the vignette. 

Alternatively the source code for the vignettes are `analysis.Rmd` `analysis-ecoli.Rmd` and `analysis-kleb.Rmd`in the `vignettes/` folder of the [GitHub](https://github.com/joelewis101/blantyreESBL)
 repo or the [pkgdown](https://joelewis101.github.io/blantyreESBL/) site for this package has a rendered version of each vignette.
 
### Running Stan models
 
The longitudinal modelling paper uses models fit with Stan, the probabilistic programming language, via the *rstan* R package. Unlike the rest if the vignettes (which run the analysis as they are built) the Stan models are not fit as part of the package vignettes as they take a long time to fit. The outputs of the models are available as data objects and a vignette provides instructions on how to fit and simulate from the posterior. The Stan code is available as .stan files in the package directory - see vignette for how to locate it.
 
### Author affiliations
 
 1. Malawi Liverpool Wellcome Clinical Research Programme, Blantyre, Malawi
2. Department of Clinical Sciences, Liverpool School of Tropical Medicine, Liverpool, UK
3. Department of Clinical Infection, Microbiology and Immunology, University of Liverpool, Liverpool, UK
4. Wellcome Sanger Institute, Hinxton, UK
5. College of Medicine, University of Malawi, Malawi
6. University of Lancaster, Lancaster, UK
7. London School of Tropical Medicine and Hygiene, London, UK 
